blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/Startap/sail-podman/discussions/categories/feature-request
    about: 'For ideas or feature requests, please go to our Community Feature Requests section'
  - name: Support question
    url: https://github.com/Startap/sail-podman/discussions/categories/q-a
    about: 'If you have any question or doubt, you can ask it in our Community QA section'
